FROM phizaz/tensorflow:gpu

########################################
# ROOT MODE
########################################
USER root
RUN pip install --no-cache-dir requests tqdm

########################################
# USER MODE
########################################
USER docker
