FROM python:2
MAINTAINER Konpat Preechakul <the.akita.ta@gmail.com>

RUN apt-get update
RUN apt-get install -y build-essential

RUN pip install numpy
RUN pip install scipy
RUN pip install scikit-learn

WORKDIR /workdir
